title: Bikash Pandey # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate about providing scalable and robust solutions from data while learning and establishing new concepts. Regular attendee of hackathons and meetups. Open source Contributor.
  <br><br>
  I like to work on web technologies with a special knack of AI. Open to Collaborations on interesting projects. I sometimes try to document my projects on youtube, feel free to drop by or hit me up with some ideas.
  Most of my projects are based on real life solutions which leverage these technologies.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a><br><br> 
  <a href="https://www.youtube.com/channel/UC1gq7L0CoaBQGnmCCa_SLqg">Visit me on Youtube</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
gems: ["jemoji"]